import type { Product, Review } from "./types";

export const demoProducts: Product[] = [
  {
    id: "demo-1",
    slug: "vitamin-d-1000iu",
    name: "Vitamin D 1000 IU",
    sku: "VD-1000",
    short_description: "Supports bone health and immunity.",
    description: "Trusted pharmaceutical-grade Vitamin D for daily maintenance.",
    benefits: ["Supports bone health", "Immune support"],
    ingredients: "Cholecalciferol (Vitamin D3)",
    usage: "Take one tablet daily with food.",
    specifications: {},
    price: 9.99,
    compare_at_price: null,
    currency: "USD",
    stock: 50,
    low_stock_threshold: 5,
    rating: 4.7,
    review_count: 12,
    images: ["/assets/demo/vitamin-d.jpg"],
    category_id: null,
    brand_id: null,
    is_published: true,
    is_featured: false,
    is_trending: true,
    is_best_seller: true,
    is_new_arrival: false,
    seo_title: null,
    meta_description: null,
    created_at: new Date().toISOString(),
  },
  {
    id: "demo-2",
    slug: "omega-3-1000mg",
    name: "Omega-3 1000mg",
    sku: "OM3-1000",
    short_description: "High potency fish oil for heart health.",
    description: "Pharmaceutical-grade omega-3 with high EPA/DHA content.",
    benefits: ["Heart support", "Cognitive health"],
    ingredients: "Fish oil (EPA/DHA)",
    usage: "Take one softgel daily.",
    specifications: {},
    price: 14.5,
    compare_at_price: null,
    currency: "USD",
    stock: 30,
    low_stock_threshold: 5,
    rating: 4.8,
    review_count: 8,
    images: ["/assets/demo/omega3.jpg"],
    category_id: null,
    brand_id: null,
    is_published: true,
    is_featured: false,
    is_trending: false,
    is_best_seller: true,
    is_new_arrival: true,
    seo_title: null,
    meta_description: null,
    created_at: new Date().toISOString(),
  },
  {
    id: "demo-3",
    slug: "probiotic-30-caps",
    name: "Probiotic 30 Caps",
    sku: "PRB-30",
    short_description: "Supports gut health and digestion.",
    description: "A balanced multi-strain probiotic formula.",
    benefits: ["Gut health", "Digestive support"],
    ingredients: "Lactobacillus, Bifidobacterium strains",
    usage: "Take one capsule daily with food.",
    specifications: {},
    price: 12.0,
    compare_at_price: null,
    currency: "USD",
    stock: 25,
    low_stock_threshold: 5,
    rating: 4.6,
    review_count: 5,
    images: ["/assets/demo/probiotic.jpg"],
    category_id: null,
    brand_id: null,
    is_published: true,
    is_featured: false,
    is_trending: true,
    is_best_seller: false,
    is_new_arrival: true,
    seo_title: null,
    meta_description: null,
    created_at: new Date().toISOString(),
  },
];

export const demoReviews: Review[] = [
  {
    id: "r-demo-1",
    product_id: "demo-1",
    author_name: "Aman K.",
    author_location: "London",
    rating: 5,
    title: "Excellent quality",
    body: "Fast delivery and the product matched the description. Highly recommend.",
    created_at: new Date().toISOString(),
    is_featured: true,
    is_approved: true,
  },
  {
    id: "r-demo-2",
    product_id: "demo-2",
    author_name: "Priya S.",
    author_location: "Manchester",
    rating: 4,
    title: "Good value",
    body: "Noticeable improvement after a few weeks. Packaging was discreet.",
    created_at: new Date().toISOString(),
    is_featured: true,
    is_approved: true,
  },
  {
    id: "r-demo-3",
    product_id: "demo-3",
    author_name: "Rahul P.",
    author_location: "Birmingham",
    rating: 5,
    title: "Works well",
    body: "No side effects and helped with digestion. Will buy again.",
    created_at: new Date().toISOString(),
    is_featured: true,
    is_approved: true,
  },
];
