
-- Clear demo storefront content
DELETE FROM public.reviews;
DELETE FROM public.product_images;
DELETE FROM public.cart_items;
DELETE FROM public.wishlist_items;
DELETE FROM public.products;
DELETE FROM public.brands;
DELETE FROM public.categories;
DELETE FROM public.blog_posts;
DELETE FROM public.faqs;
DELETE FROM public.banners;

INSERT INTO public.categories (slug, name, description, image_url, sort_order, is_visible) VALUES
('oral-treatments','Oral Treatments','Tablet and capsule formulations, dosed and blister sealed.','https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&w=900&q=80',1,true),
('injectables','Injectables','Sterile ampoules and multi-dose vials from licensed labs.','https://images.unsplash.com/photo-1587854692152-cbe660dbde88?auto=format&fit=crop&w=900&q=80',2,true),
('post-cycle-support','Post-Cycle Support','Recovery protocols to restore natural balance after a course.','https://images.unsplash.com/photo-1631549916768-4119b2e5f926?auto=format&fit=crop&w=900&q=80',3,true),
('peptides-hgh','Peptides & HGH','Lyophilised peptides and growth hormone, cold-chain shipped.','https://images.unsplash.com/photo-1603398938378-e54eab446dde?auto=format&fit=crop&w=900&q=80',4,true),
('fat-loss','Fat Loss','Thermogenic and metabolic support, clinically dosed.','https://images.unsplash.com/photo-1550572017-edd951b55104?auto=format&fit=crop&w=900&q=80',5,true),
('sexual-health','Sexual Health','Discreet ED and libido treatments in plain packaging.','https://images.unsplash.com/photo-1607619056574-7b8d3ee536b2?auto=format&fit=crop&w=900&q=80',6,true),
('wellness','Wellness & Vitamins','Daily support: vitamins, liver care and joint formulas.','https://images.unsplash.com/photo-1576671081837-49000212a370?auto=format&fit=crop&w=900&q=80',7,true);

WITH c AS (SELECT slug, id FROM public.categories)
INSERT INTO public.products
(slug,name,sku,short_description,description,benefits,usage,ingredients,specifications,price,compare_at_price,currency,stock,low_stock_threshold,rating,review_count,images,category_id,is_published,is_featured,is_trending,is_best_seller,is_new_arrival,seo_title,meta_description)
VALUES
('oxandrolone-10mg','Oxandrolone 10mg Tablets','HLX-OXA-10','Mild oral compound in 100-tablet blister packs, HPLC verified.','Oxandrolone 10mg is a well tolerated oral compound supplied in sealed blister strips of 25. Each batch is HPLC tested for purity and dosage accuracy, with the certificate of analysis published against the batch code printed on the carton.',ARRAY['Lean tissue retention during a calorie deficit','Low aromatisation profile','Blister sealed with verifiable batch code'],'Dosage should be established with a clinician. Typical protocols run 6–8 weeks with regular bloodwork.','Oxandrolone 10mg, microcrystalline cellulose, magnesium stearate, lactose monohydrate.','{"Form":"Tablet","Strength":"10mg","Pack size":"100 tablets","Storage":"15–25°C, dry"}'::jsonb,64.99,79.99,'GBP',48,10,4.8,36,ARRAY['https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&w=900&q=80','https://images.unsplash.com/photo-1550572017-edd951b55104?auto=format&fit=crop&w=900&q=80'],(SELECT id FROM c WHERE slug='oral-treatments'),true,true,true,true,false,'Oxandrolone 10mg Tablets — Medi Pharma UK','Lab-tested Oxandrolone 10mg oral tablets, 100 per pack, dispatched discreetly from the UK.'),
('stanozolol-10mg','Stanozolol 10mg Tablets','HLX-STA-10','Dry oral compound, 100 tablets, third-party assayed.','Stanozolol 10mg tablets are produced under GMP conditions and independently assayed. Supplied in a tamper-evident carton with an inner blister strip and printed batch and expiry data.',ARRAY['Non-aromatising oral option','Consistent 10mg dosing per tablet','Independent assay certificate per batch'],'Commonly used in short 6-week protocols. Liver support and hydration are advised throughout.','Stanozolol 10mg, lactose, croscarmellose sodium, magnesium stearate.','{"Form":"Tablet","Strength":"10mg","Pack size":"100 tablets","Storage":"Below 25°C"}'::jsonb,49.99,NULL,'GBP',62,10,4.7,28,ARRAY['https://images.unsplash.com/photo-1631549916768-4119b2e5f926?auto=format&fit=crop&w=900&q=80'],(SELECT id FROM c WHERE slug='oral-treatments'),true,false,true,true,false,'Stanozolol 10mg Tablets — Medi Pharma UK','Stanozolol 10mg oral tablets, GMP produced and independently assayed. UK next-day delivery.'),
('dianabol-10mg','Methandienone 10mg Tablets','HLX-MET-10','Classic oral compound, 100 tablets per sealed carton.','Methandienone 10mg in a 100-tablet carton. Each production run is sampled and tested for identity, potency and heavy metals before release.',ARRAY['Fast-acting oral formulation','Accurate 10mg split scoring','Full certificate of analysis online'],'Short cycles only, with blood pressure and liver markers monitored.','Methandienone 10mg, dicalcium phosphate, starch, magnesium stearate.','{"Form":"Tablet","Strength":"10mg","Pack size":"100 tablets","Storage":"Dry, below 25°C"}'::jsonb,42.5,54.0,'GBP',75,10,4.6,44,ARRAY['https://images.unsplash.com/photo-1585435557343-3b092031a831?auto=format&fit=crop&w=900&q=80'],(SELECT id FROM c WHERE slug='oral-treatments'),true,false,false,true,false,'Methandienone 10mg Tablets — Medi Pharma UK','Methandienone 10mg oral tablets, batch tested and shipped discreetly from the UK.'),
('testosterone-enanthate-250','Testosterone Enanthate 250mg/ml','HLX-TES-250','10ml sterile multi-dose vial, filtered and sealed.','Testosterone Enanthate 250mg/ml supplied in a 10ml amber multi-dose vial with a flip-off seal. Sterile filtered at 0.22 micron and filled in a clean room.',ARRAY['Long ester, weekly dosing','Sterile filtered 0.22 micron','Amber glass protects the solution'],'Intramuscular use only, under clinical guidance. Rotate injection sites.','Testosterone enanthate 250mg, grapeseed oil, benzyl alcohol 2%, benzyl benzoate.','{"Form":"Oil solution","Strength":"250mg/ml","Volume":"10ml vial","Storage":"15–25°C, protect from light"}'::jsonb,38.0,NULL,'GBP',90,12,4.9,71,ARRAY['https://images.unsplash.com/photo-1587854692152-cbe660dbde88?auto=format&fit=crop&w=900&q=80','https://images.unsplash.com/photo-1628771065518-0d82f1938462?auto=format&fit=crop&w=900&q=80'],(SELECT id FROM c WHERE slug='injectables'),true,true,true,true,false,'Testosterone Enanthate 250mg/ml — Medi Pharma UK','Sterile Testosterone Enanthate 250mg/ml 10ml vial, lab verified. Discreet UK delivery.'),
('nandrolone-decanoate-300','Nandrolone Decanoate 300mg/ml','HLX-NAN-300','10ml vial, smooth carrier oil, low injection discomfort.','Nandrolone Decanoate 300mg/ml in a 10ml vial. The low-viscosity carrier reduces injection discomfort while keeping the solution stable across its shelf life.',ARRAY['Long acting decanoate ester','Low viscosity, smoother injection','Batch code verifiable online'],'Intramuscular use only. Typically dosed once weekly under supervision.','Nandrolone decanoate 300mg, grapeseed oil, benzyl alcohol, benzyl benzoate.','{"Form":"Oil solution","Strength":"300mg/ml","Volume":"10ml vial","Storage":"Below 25°C"}'::jsonb,45.0,52.0,'GBP',54,10,4.7,33,ARRAY['https://images.unsplash.com/photo-1628771065518-0d82f1938462?auto=format&fit=crop&w=900&q=80'],(SELECT id FROM c WHERE slug='injectables'),true,false,true,false,false,'Nandrolone Decanoate 300mg/ml — Medi Pharma UK','Nandrolone Decanoate 300mg/ml 10ml sterile vial, third-party tested, UK dispatch.'),
('trenbolone-acetate-100','Trenbolone Acetate 100mg/ml','HLX-TRA-100','10ml vial for advanced users, clean room filled.','Trenbolone Acetate 100mg/ml, filled and sealed under ISO clean room conditions and released only after sterility and endotoxin testing.',ARRAY['Short ester with rapid clearance','Sterility and endotoxin tested','Tamper-evident flip-off seal'],'Advanced users only. Frequent dosing schedules; monitor cardiovascular markers.','Trenbolone acetate 100mg, grapeseed oil, benzyl alcohol, benzyl benzoate.','{"Form":"Oil solution","Strength":"100mg/ml","Volume":"10ml vial","Storage":"15–25°C"}'::jsonb,52.0,NULL,'GBP',30,8,4.8,21,ARRAY['https://images.unsplash.com/photo-1603398938378-e54eab446dde?auto=format&fit=crop&w=900&q=80'],(SELECT id FROM c WHERE slug='injectables'),true,false,false,false,true,'Trenbolone Acetate 100mg/ml — Medi Pharma UK','Trenbolone Acetate 100mg/ml 10ml vial, clean room filled and sterility tested.'),
('tamoxifen-20mg','Tamoxifen 20mg Tablets','HLX-TAM-20','Oestrogen control in a 50-tablet blister pack.','Tamoxifen citrate 20mg tablets, blister packed in strips of 25. A staple of most recovery protocols, tested for content uniformity on every run.',ARRAY['Supports hormonal recovery','Content uniformity tested','Blister packed for stability'],'Usually started after the last active compound clears. Follow a clinician-guided taper.','Tamoxifen citrate 20mg, lactose, starch, magnesium stearate.','{"Form":"Tablet","Strength":"20mg","Pack size":"50 tablets","Storage":"Below 25°C"}'::jsonb,24.99,29.99,'GBP',120,15,4.6,52,ARRAY['https://images.unsplash.com/photo-1576671081837-49000212a370?auto=format&fit=crop&w=900&q=80'],(SELECT id FROM c WHERE slug='post-cycle-support'),true,true,false,true,false,'Tamoxifen 20mg Tablets — Medi Pharma UK','Tamoxifen citrate 20mg tablets for post-cycle support, 50 per pack, UK stocked.'),
('clomiphene-50mg','Clomiphene 50mg Tablets','HLX-CLO-50','Recovery support, 30 tablets, sealed blister.','Clomiphene citrate 50mg tablets used within structured recovery protocols. Supplied with batch documentation and expiry printed on the carton.',ARRAY['Restores natural production post-course','Precise 50mg dosing','Independently verified batch'],'Typical protocols run 3–4 weeks with tapering. Bloodwork before and after is recommended.','Clomiphene citrate 50mg, lactose, maize starch, magnesium stearate.','{"Form":"Tablet","Strength":"50mg","Pack size":"30 tablets","Storage":"Dry, below 25°C"}'::jsonb,27.5,NULL,'GBP',88,15,4.5,19,ARRAY['https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&w=900&q=80'],(SELECT id FROM c WHERE slug='post-cycle-support'),true,false,false,false,false,'Clomiphene 50mg Tablets — Medi Pharma UK','Clomiphene citrate 50mg tablets for post-cycle recovery. Discreet UK delivery.'),
('anastrozole-1mg','Anastrozole 1mg Tablets','HLX-ANA-1','Aromatase control, 30 tablets per pack.','Anastrozole 1mg tablets for oestrogen management. Scored for accurate splitting and tested for potency on every production batch.',ARRAY['Precise aromatase control','Scored for half doses','Potency tested per batch'],'Low doses, adjusted to symptoms and bloodwork. Do not exceed clinician guidance.','Anastrozole 1mg, lactose monohydrate, povidone, magnesium stearate.','{"Form":"Tablet","Strength":"1mg","Pack size":"30 tablets","Storage":"Below 25°C"}'::jsonb,22.0,NULL,'GBP',96,15,4.7,24,ARRAY['https://images.unsplash.com/photo-1631549916768-4119b2e5f926?auto=format&fit=crop&w=900&q=80'],(SELECT id FROM c WHERE slug='post-cycle-support'),true,false,false,false,true,'Anastrozole 1mg Tablets — Medi Pharma UK','Anastrozole 1mg tablets, potency tested, for oestrogen management. UK dispatch.'),
('somatropin-100iu','Somatropin HGH 100IU Kit','HLX-HGH-100','Ten 10IU vials, cold-chain shipped with bacteriostatic water.','A 100IU somatropin kit containing ten lyophilised 10IU vials. Shipped in insulated cold-chain packaging with bacteriostatic water included.',ARRAY['Lyophilised for shelf stability','Cold-chain insulated shipping','Bacteriostatic water included'],'Reconstitute with the supplied water and refrigerate. Use within 14 days of reconstitution.','Somatropin (rDNA origin) 10IU per vial, mannitol, glycine, sodium phosphate.','{"Form":"Lyophilised powder","Strength":"10IU per vial","Kit size":"10 vials (100IU)","Storage":"2–8°C after mixing"}'::jsonb,189.0,229.0,'GBP',22,5,4.9,17,ARRAY['https://images.unsplash.com/photo-1603398938378-e54eab446dde?auto=format&fit=crop&w=900&q=80','https://images.unsplash.com/photo-1587854692152-cbe660dbde88?auto=format&fit=crop&w=900&q=80'],(SELECT id FROM c WHERE slug='peptides-hgh'),true,true,true,false,true,'Somatropin HGH 100IU Kit — Medi Pharma UK','Somatropin 100IU kit with ten 10IU vials, cold-chain shipped across the UK.'),
('bpc-157-5mg','BPC-157 5mg Peptide Vial','HLX-BPC-5','Research peptide, 5mg lyophilised, 99% purity assay.','BPC-157 5mg supplied as a lyophilised powder in a sealed vial with a 99%+ purity assay published against the batch code.',ARRAY['99%+ HPLC purity','Lyophilised for long shelf life','Assay published per batch'],'Reconstitute with bacteriostatic water and refrigerate. Follow research protocol guidance.','BPC-157 pentadecapeptide 5mg, mannitol.','{"Form":"Lyophilised powder","Strength":"5mg","Pack size":"1 vial","Storage":"2–8°C reconstituted"}'::jsonb,34.0,NULL,'GBP',64,10,4.8,26,ARRAY['https://images.unsplash.com/photo-1628771065518-0d82f1938462?auto=format&fit=crop&w=900&q=80'],(SELECT id FROM c WHERE slug='peptides-hgh'),true,false,true,false,true,'BPC-157 5mg Peptide Vial — Medi Pharma UK','BPC-157 5mg lyophilised peptide with 99% purity assay. UK cold-chain dispatch.'),
('clenbuterol-40mcg','Clenbuterol 40mcg Tablets','HLX-CLE-40','Thermogenic support, 100 tablets per blister carton.','Clenbuterol hydrochloride 40mcg tablets in a 100-tablet carton, dose verified on every batch.',ARRAY['Consistent 40mcg dosing','Thermogenic metabolic support','Blister sealed carton'],'Cycled use with careful heart-rate monitoring. Not for use with stimulants.','Clenbuterol hydrochloride 40mcg, lactose, starch, magnesium stearate.','{"Form":"Tablet","Strength":"40mcg","Pack size":"100 tablets","Storage":"Below 25°C"}'::jsonb,29.99,36.0,'GBP',110,15,4.5,48,ARRAY['https://images.unsplash.com/photo-1550572017-edd951b55104?auto=format&fit=crop&w=900&q=80'],(SELECT id FROM c WHERE slug='fat-loss'),true,false,true,true,false,'Clenbuterol 40mcg Tablets — Medi Pharma UK','Clenbuterol 40mcg tablets, dose verified per batch, dispatched discreetly in the UK.'),
('t3-liothyronine-25mcg','T3 Liothyronine 25mcg Tablets','HLX-LIO-25','Thyroid support, 100 tablets, potency verified.','Liothyronine sodium 25mcg tablets for metabolic support, released only after potency and dissolution testing.',ARRAY['Verified 25mcg potency','Dissolution tested','Scored for accurate titration'],'Titrate slowly and taper off. Thyroid panels before and after use are advised.','Liothyronine sodium 25mcg, lactose, starch, magnesium stearate.','{"Form":"Tablet","Strength":"25mcg","Pack size":"100 tablets","Storage":"Dry, below 25°C"}'::jsonb,32.0,NULL,'GBP',70,12,4.4,15,ARRAY['https://images.unsplash.com/photo-1576671081837-49000212a370?auto=format&fit=crop&w=900&q=80'],(SELECT id FROM c WHERE slug='fat-loss'),true,false,false,false,false,'T3 Liothyronine 25mcg Tablets — Medi Pharma UK','Liothyronine 25mcg tablets, potency and dissolution tested. UK next-day dispatch.'),
('sildenafil-100mg','Sildenafil 100mg Tablets','HLX-SIL-100','ED treatment, 20 film-coated tablets, plain packaging.','Sildenafil citrate 100mg film-coated tablets supplied in discreet plain packaging with no reference to contents on the outer label.',ARRAY['Film coated for easier dosing','Scored for 50mg halves','Completely plain outer packaging'],'One tablet as needed, no more than once in 24 hours. Not to be combined with nitrates.','Sildenafil citrate 100mg, lactose, hypromellose, titanium dioxide.','{"Form":"Film-coated tablet","Strength":"100mg","Pack size":"20 tablets","Storage":"Below 25°C"}'::jsonb,19.99,26.0,'GBP',150,20,4.8,96,ARRAY['https://images.unsplash.com/photo-1607619056574-7b8d3ee536b2?auto=format&fit=crop&w=900&q=80'],(SELECT id FROM c WHERE slug='sexual-health'),true,true,true,true,false,'Sildenafil 100mg Tablets — Medi Pharma UK','Sildenafil 100mg film-coated tablets, 20 per pack, delivered in plain packaging.'),
('tadalafil-20mg','Tadalafil 20mg Tablets','HLX-TAD-20','Long-acting ED treatment, 20 tablets, discreet delivery.','Tadalafil 20mg tablets with an extended duration of action, blister packed and shipped in unbranded packaging.',ARRAY['Up to 36 hours duration','Blister packed for stability','Unbranded discreet delivery'],'One tablet as required, maximum one per day. Avoid with nitrate medication.','Tadalafil 20mg, lactose, croscarmellose sodium, hypromellose.','{"Form":"Film-coated tablet","Strength":"20mg","Pack size":"20 tablets","Storage":"Below 25°C"}'::jsonb,22.99,NULL,'GBP',140,20,4.8,84,ARRAY['https://images.unsplash.com/photo-1585435557343-3b092031a831?auto=format&fit=crop&w=900&q=80'],(SELECT id FROM c WHERE slug='sexual-health'),true,false,true,true,false,'Tadalafil 20mg Tablets — Medi Pharma UK','Tadalafil 20mg tablets with up to 36 hour duration. Plain packaging, UK dispatch.'),
('liver-support-complex','Liver Support Complex','HLX-LIV-90','90 capsules of milk thistle, NAC and TUDCA.','A daily liver support formula combining milk thistle extract, N-acetylcysteine and TUDCA in a 90-capsule bottle — designed to sit alongside any oral protocol.',ARRAY['TUDCA, NAC and silymarin in one capsule','30-day supply per bottle','Third-party purity tested'],'Take one capsule twice daily with food throughout any oral course.','Silymarin 300mg, N-acetylcysteine 600mg, TUDCA 250mg, vegetable capsule shell.','{"Form":"Capsule","Pack size":"90 capsules","Serving":"2 per day","Storage":"Cool, dry place"}'::jsonb,26.5,32.0,'GBP',180,20,4.9,63,ARRAY['https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&w=900&q=80'],(SELECT id FROM c WHERE slug='wellness'),true,true,false,true,true,'Liver Support Complex — Medi Pharma UK','Milk thistle, NAC and TUDCA liver support capsules, 90 per bottle. UK delivery.');

INSERT INTO public.reviews (product_id, author_name, author_location, rating, title, body, is_featured, is_approved)
SELECT p.id, v.author, v.loc, v.rating, v.title, v.body, v.feat, true
FROM (VALUES
 ('testosterone-enanthate-250','James H.','Manchester',5,'Exactly as described','Ordered Tuesday afternoon, arrived Wednesday in plain packaging. Batch code matched the test report on the site.',true),
 ('sildenafil-100mg','Daniel P.','Bristol',5,'Discreet and quick','No branding on the parcel at all and the tracking was accurate to the hour. Will reorder.',true),
 ('liver-support-complex','Owen R.','Leeds',5,'Now part of my routine','Bloodwork came back better than my last course. Good value for a 90 capsule bottle.',true),
 ('oxandrolone-10mg','Michael T.','Glasgow',5,'Genuine product','Blister sealed, expiry printed, and customer service answered a dosing question on a Sunday.',true),
 ('somatropin-100iu','Alex W.','London',5,'Cold chain intact','Arrived cold with ice packs still solid. Impressed with the packaging standard.',false),
 ('clenbuterol-40mcg','Ryan D.','Cardiff',4,'Does the job','Solid product, delivery was a day later than expected but support kept me updated.',false)
) AS v(slug, author, loc, rating, title, body, feat)
JOIN public.products p ON p.slug = v.slug;

INSERT INTO public.blog_posts (slug,title,excerpt,content,cover_image_url,author_name,category,read_minutes,seo_title,meta_description,is_published,published_at) VALUES
('how-we-batch-test','How every Medi batch is tested before it reaches you','A walk through the lab process behind each batch code printed on our cartons.','Every product we list is sampled from the finished production run and sent to an independent UK laboratory. We test for identity, potency, dissolution and heavy metals.

If a batch falls outside a 5% tolerance on stated dosage, it is rejected outright — not discounted, not relabelled. The certificate of analysis is then published against the batch code printed on the carton, so you can match the box in your hand to the report on this site.','https://images.unsplash.com/photo-1631549916768-4119b2e5f926?auto=format&fit=crop&w=1200&q=80','Dr. Amelia Rowe','Quality',6,'How Medi Pharma batch tests every product','Inside the independent lab testing behind every batch code on a Medi Pharma carton.',true,now() - interval '9 days'),
('post-cycle-recovery-guide','A practical guide to post-cycle recovery','What the evidence says about restoring natural production after a course.','Recovery planning should start before a course does. This guide covers timing, the role of SERMs, why bloodwork matters more than forum protocols, and the markers worth tracking at four and twelve weeks.

None of this replaces a clinician. Use it as a framework for the conversation, not a substitute for it.','https://images.unsplash.com/photo-1576671081837-49000212a370?auto=format&fit=crop&w=1200&q=80','Dr. Amelia Rowe','Guides',8,'A practical guide to post-cycle recovery','Evidence-led guidance on planning post-cycle recovery, timing and the bloodwork that matters.',true,now() - interval '20 days'),
('storing-peptides-correctly','Storing peptides and HGH correctly at home','Cold chain does not end at your front door — here is how to keep potency.','Lyophilised peptides are stable at room temperature for short periods, but once reconstituted the clock starts. We cover fridge placement, avoiding freeze-thaw cycles, bacteriostatic versus sterile water, and how long a mixed vial realistically lasts.','https://images.unsplash.com/photo-1603398938378-e54eab446dde?auto=format&fit=crop&w=1200&q=80','Nadia Kaur','Storage',5,'Storing peptides and HGH correctly at home','How to store lyophilised and reconstituted peptides at home without losing potency.',true,now() - interval '32 days');

INSERT INTO public.faqs (question, answer, category, position, is_visible) VALUES
('How quickly will my order arrive?','Orders placed before 3pm on a working day are dispatched the same day. UK tracked delivery is next working day; free on orders over £100.','Delivery',1,true),
('Is the packaging discreet?','Yes. Every parcel is sent in plain, unbranded outer packaging with no reference to the contents, and the sender name on the label is neutral.','Delivery',2,true),
('How do I verify a batch is genuine?','Each carton carries a batch code. Enter it on the product page to view the matching third-party certificate of analysis.','Quality',3,true),
('Do you provide medical advice?','No. Our team can answer questions about products, storage and delivery, but dosing and suitability must be discussed with a qualified clinician.','Using our products',4,true),
('What payment methods do you accept?','All major debit and credit cards, plus bank transfer for larger orders. Card statements show a neutral descriptor.','Payments',5,true),
('Can I return an item?','Sealed, unopened items can be returned within 30 days. For safety reasons we cannot accept opened medication or cold-chain products.','Returns',6,true),
('Do you ship outside the UK?','We ship across the UK and to selected EU destinations. Cold-chain items are UK mainland only.','Delivery',7,true),
('How should I store my order?','Most products are stable below 25°C in a dry place. Peptides and HGH must be refrigerated at 2–8°C once reconstituted.','Storage',8,true);

INSERT INTO public.banners (title, subtitle, eyebrow, image_url, cta_label, cta_url, placement, position, is_active) VALUES
('Free discreet UK delivery over £100','Same-day dispatch on orders placed before 3pm.','Autumn restock','https://images.unsplash.com/photo-1587854692152-cbe660dbde88?auto=format&fit=crop&w=1600&q=80','Shop all products','/shop','home_hero',1,true);

UPDATE public.pages SET
  title = CASE slug
    WHEN 'about' THEN 'About Medi Pharma UK'
    WHEN 'contact' THEN 'Contact our care team'
    ELSE title END,
  subtitle = CASE slug
    WHEN 'about' THEN 'A UK supplier of lab-verified, pharmacy-grade medication.'
    WHEN 'contact' THEN 'Seven days a week, from our Manchester support desk.'
    ELSE subtitle END
WHERE slug IN ('about','contact');

INSERT INTO public.settings (key, value) VALUES
('site', '{"name":"Medi Pharma UK","tagline":"Pharmacy-grade medicine, verified batch by batch","currency":"GBP","logo_url":null,"favicon_url":null}'::jsonb),
('contact', '{"email":"care@Medipharma.co.uk","phone":"+44 161 555 0142","address":"Unit 12 Trafford Point, Manchester M17 1AB, United Kingdom","hours":"Mon–Sun, 8am–8pm"}'::jsonb),
('social', '{"instagram":"https://instagram.com/Medipharmauk","x":"https://x.com/Medipharmauk","facebook":""}'::jsonb),
('seo', '{"default_title":"Medi Pharma UK — Pharmacy-Grade Medicines Delivered","default_description":"Lab-tested pharmacy-grade medication, performance support and wellness treatments, dispatched discreetly from the UK."}'::jsonb)
ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value, updated_at = now();
